system:
  env: local
  db-type: ENC(FG2VKsgGpIRdeX9gejejWK5cYXrosSF8rxVL5Kpy+9bYBxFWBaQ1MTYfWWX7KNEX)
  use-redis: ENC(dM9C7o7Tr9fglTEJohsWOo/bQEx6ZLthU/1b1bFuuc5/EkuRuasXrLVlPHhEevkI)

zap:
  level: debug
  prefix: '[github.com/alice52/bili-video-archive]'
  format: json   # console
  director: logs
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true
